/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chrulri_droidoflife_LifeRuntime */

#ifndef _Included_com_chrulri_droidoflife_LifeRuntime
#define _Included_com_chrulri_droidoflife_LifeRuntime
#ifdef __cplusplus
extern "C" {
#endif
#undef com_chrulri_droidoflife_LifeRuntime_OK
#define com_chrulri_droidoflife_LifeRuntime_OK 0L
/*
 * Class:     com_chrulri_droidoflife_LifeRuntime
 * Method:    nRuntimeInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_chrulri_droidoflife_LifeRuntime_nRuntimeInit
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_chrulri_droidoflife_LifeRuntime
 * Method:    nRuntimeIterate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chrulri_droidoflife_LifeRuntime_nRuntimeIterate
  (JNIEnv *, jclass);

/*
 * Class:     com_chrulri_droidoflife_LifeRuntime
 * Method:    nRuntimeDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chrulri_droidoflife_LifeRuntime_nRuntimeDestroy
  (JNIEnv *, jclass);

/*
 * Class:     com_chrulri_droidoflife_LifeRuntime
 * Method:    nGLrender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chrulri_droidoflife_LifeRuntime_nGLrender
  (JNIEnv *, jclass);

/*
 * Class:     com_chrulri_droidoflife_LifeRuntime
 * Method:    nGLresize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_chrulri_droidoflife_LifeRuntime_nGLresize
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
